### ISSUE TITLE
标准模式输出了错误的Json格式

### ISSUE THREAD

**Issue by TowardtheStars** [Snownee/Item-Render-Dark#1]
* Minecraft Version: 1.12.2
 * Mod Version: 0.3.1

在配置中设置"ExportFormat=standard"后, 输出的json文件拥有多个根标签, 如下所示:
```
{......},
{......},
 ......
{......}
```

而每个json文件中应当只有一个根标签. 在此建议将这些内容打包成数组输出, 如下:
```
[
  {......},
  {......},
   ......,
  {......}
]
```

**Comment by Snownee** [comment]
这是故意的……
